name = "ivy-blog-bot"
main = "src/index.ts"
compatibility_date = "2026-06-01"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "IVY_KV"
id = "9dfd92f4487a4c0aa6114b60b5c9127b"

[triggers]
crons = ["* * * * *"]
